stages:
  ingestion:
    cmd: python src/data/ingestion.py
    deps:
      - src/data/ingestion.py
      - params.yaml
    outs:
      - data/raw/train.csv
      - data/raw/test.csv

  preprocessing:
    cmd: python src/data/preprocessing.py
    deps:
      - src/data/preprocessing.py
      - data/raw/train.csv
      - data/raw/test.csv
      - params.yaml
    outs:
      - data/processed/train.csv
      - data/processed/test.csv

  training:
    cmd: python src/model/model_building.py
    deps:
      - src/model/model_building.py
      - data/processed/train.csv
      - params.yaml
    outs:
      - models/lgbm_model.pkl
      - models/tfidf_vectorizer.pkl

  evaluation:
    cmd: python src/model/evaluate.py
    deps:
      - src/model/evaluate.py
      - models/lgbm_model.pkl
      - models/tfidf_vectorizer.pkl
      - data/processed/test.csv
      - params.yaml
    outs:
      - models/classification_report.json
      - models/confusion_matrix_test.png
      - models/run_info.json
